### ISSUE TITLE
delete CILogon staged certificate

### ISSUE THREAD

**Issue by zonca** [jupyter/oauthenticator#18]
@minrk I am wondering whether it would be useful to delete the staged certificate and only keep the encrypted version.

While the user is connected, `poll` is probably continuously using the certificate.
Is there a way to detect if the user is not connected, maybe with a timeout, and delete the staged certificate at that point?

**Comment by minrk** [comment]
In what context? The cert isn't used for anything at all, here.  You can check the last_activity of a user, to see how long it's been since they've been seen. The resolution isn't better than about 5 minutes, though.

**Comment by zonca** [comment]
in the context of a spawner that uses the CILogon certificate.
It would be useful to have an unstage method that the spawner can call once `jupyterhub-singleuser` exits. This way we do not keep around an unencrypted cert if not needed (let's assume TPM encryption).

So here the timeline:
* user authenticates with `oauthenticator` and gets a certificate stored encrypted with TPM or some other way
* `CILogonSpawnerMixin` stages the certificate
* the spawner starts `jupyterhub-singleuser`
* when `jupyterhub-singleuser` exits, the certificate it still around, I'd rather delete it for security

**Comment by minrk** [comment]
#20 unstages the certificate file after it stops.

**Comment by zonca** [comment]
Awesome, thanks!
