### ISSUE TITLE
GithubOAuthenticator gets 403

### ISSUE THREAD

**Issue by jzmiller1** [jupyter/oauthenticator#8]
I attempted to get oauthenticator up and running and ran into a few issues.  I had to change my settings as the examples provided didn't work (I addressed this in PR #7 ).   After the settings change I was able to hit my jupyterhub server and log in through github.  I was properly forwarded to GitHub and authorized my server for logins and forwarded back to my callback url but I recieved a 403.

The url was:

hub/oauth_callback?code=280e308d237c1849e446

I saw in my server log something about a missing auth_token key during one run through but now all I get is:

[W 2015-07-25 02:05:00.725 JupyterHub log:100] 403 GET /hub/oauth_callback?code=280e308d237c1849e446 311.85ms

I hope this is making some sense.  I dont know enough to try to troubleshoot any further.

**Comment by minrk** [comment]
I've restored the deprecated names with a message, and tested that current master does work properly with GitHub. The thing to make sure is that you've got all three variables set properly, on GitHub as well as in your jupyterhub_config.
